Repository PatilHarshh/Kaam-Do, pull requests merged in 2024-06, with the labels that each got.

#177 search Category section card update
  client/src/components/About/Home/SectionSecond.jsx
  client/src/components/Home/SectionSecond.jsx
Labels: gssoc, level1

#190 Added pictures
  .idea/.gitignore
  client/src/components/Home/SectionFourth.jsx
  client/src/components/Home/SectionSixth.jsx
  server/package.json
Labels: gssoc, level1

#197 feat:Add Scroll to Top Button
  client/src/App.jsx
  client/src/components/About/About.jsx
  client/src/pages/Companies.jsx
  client/src/pages/FindJobs.jsx
Labels: gssoc, level1

#205 footer redesign
  client/src/components/Footer.jsx
Labels: gssoc, level1

#225 auto close issues
  .github/workflows/close-issues.yml
Labels: gssoc, level1

#228 user search category then display that category
  client/src/components/Home/SectionSecond.jsx
Labels: gssoc, level2

#218 [Bug]: Updated the docs
  README.md
Labels: gssoc, level1

#206 added code of conduct
  CODE_OF_CONDUCT.md
Labels: gssoc, level1

#244 Feat:Dark mode theme for website #201
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/About/Home/SectionFirst.jsx
  client/src/components/About/Home/SectionSecond.jsx
  client/src/components/About/Home/SectionThird.jsx
  client/src/components/About/SectionFirst.jsx
  client/src/components/About/SectionFourth.jsx
  client/src/components/About/SectionSecond.jsx
  client/src/components/About/SectionThird.jsx
  client/src/components/CompanyCard.jsx
  client/src/components/DarkMode/DarkMode.jsx
  client/src/components/DarkMode/moon.webp
  client/src/components/DarkMode/sun.png
  client/src/components/Footer.jsx
  client/src/components/Header.jsx
  client/src/components/Home/SectionFifth.jsx
  client/src/components/Home/SectionFirst.jsx
  client/src/components/Home/SectionFourth.jsx
  client/src/components/Home/SectionSecond.jsx
  client/src/components/Home/SectionSixth.jsx
  client/src/components/Home/SectionThird.jsx
  client/src/components/JobCard.jsx
  client/src/components/JobTypes.jsx
  client/src/components/Navbar.jsx
  client/src/index.css
  client/src/pages/Companies.jsx
  client/src/pages/CompanyProfile.jsx
  client/src/pages/FindJobs.jsx
  client/src/pages/JobDetail.jsx
  client/src/pages/UploadJob.jsx
  client/tailwind.config.js
  client/vite.config.js
Labels: gssoc, level2

#213 successfuly fetching blogs from Medium Api
  client/dist/assets/codewave-b6bf4c85.png
  client/dist/assets/facebook-2f54914b.png
  client/dist/assets/google-b9f2dce9.png
  client/dist/assets/hero-39b48dbc.png
  client/dist/assets/index-1f76e8ca.js
  client/dist/assets/index-4d8c9364.css
  client/dist/assets/instagram-496c0b62.png
  client/dist/assets/job-7a3982a9.jpg
  client/dist/assets/linkedin-7dcbc614.png
  client/dist/assets/office-095f6b2e.jpg
  client/dist/assets/spotify-a4ba38da.png
  client/dist/assets/twitter-e6ca9110.png
  client/dist/assets/userprofile-028bf096.png
  client/dist/assets/vendor-9d70f441.js
  client/dist/assets/whatsapp-e4e23ecf.png
  client/dist/assets/youtube-558740da.png
  client/dist/index.html
  client/dist/vite.svg
  client/src/App.jsx
  client/src/pages/blogs.jsx
  client/src/pages/index.js
  client/vite.config.js
  package-lock.json
  package.json
Labels: gssoc, level3

#258 Scrollbar style added
  client/src/index.css
Labels: gssoc, level1

#221 Feat : Added Resume Builder
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/DarkMode/DarkMode.jsx
  client/src/components/Navbar.jsx
  client/src/pages/Resume.css
  client/src/pages/Resumebuilder.jsx
  client/src/pages/index.js
Labels: gssoc, level2

#189 Added contact form
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/ContactForm.jsx
  client/src/components/Footer.jsx
  client/src/pages/Resumebuilder.jsx
  client/src/utils/data.js
Labels: gssoc, level2

#250 footer
  client/dist/assets/index-15a02efe.js
  client/dist/assets/index-194d5343.css
  client/dist/assets/index-1f76e8ca.js
  client/dist/assets/index-4d8c9364.css
  client/dist/assets/sun-de1aa93e.png
  client/dist/assets/vendor-9d70f441.js
  client/dist/assets/vendor-ccd23c5f.js
  client/dist/index.html
  client/src/components/Footer.jsx
  package-lock.json
Labels: gssoc, level1

#278 HR image fix
  client/src/components/Home/SectionSecond.jsx
Labels: gssoc, level1

#305 Hamburger and cross icons are now visible in every mode.
  client/src/components/Navbar.jsx
Labels: gssoc, level1

#304 add some content in stay up to date
  client/package.json
  client/src/components/Home/SectionFifth.jsx
Labels: gssoc, level1
